('Sel'),
('Poivre'),
('Farine'),
('Oeufs'),
('Beurre'),
('Sucre'),
('Huile'),
('Lait'),
('Tomate'),
('Oignon'),
('chou vert'),
('Ail'),
('Pomme de terre'),
('Carotte'),
('Poulet'),
('Boeuf'),
('Porc'),
('Poisson'),
('Crevette'),
('Riz'),
('Pâtes'),
('Bouillon de poulet'),
('Bouillon de boeuf'),
('Vinaigre'),
('Moutarde'),
('Ketchup'),
('Mayonnaise'),
('Crème fraîche'),
('Fromage'),
('Pain'),
('Viande hachée'),
('Jambon'),
('Thon'),
('Saumon'),
('Morue'),
('pâte feuilletée'),
('Miel'),
("Sirop d'érable"),
('Chocolat'),
('Café'),
('Thé'),
('Rhum'),
('Vin rouge'),
('Bières'),
('Whisky'),
('Vodka'),
('Gin'),
('Tequila'),
('Ricard'),
('Martini'),
('Cointreau'),
('Triple sec'),
('Campari'),
('Baileys'),
('Cognac'),
('Armagnac'),
('Chartreuse'),
('Sambuca'),
('Limonecello'),
('Amaretto'),
('Curacao'),
('Grand Marnier'),
('Curaçao bleu'),
('Curaçao rouge'),
('Curacao vert'),
('Galliano'),
('Marasquin'),
('Midori'),
('Passoa'),
('Pernod'),
('Porto'),
('Pousse café'),
('Ratafia'),
('Sherry'),
('Southern Comfort'),
('Vermouth'),
('Curaçao blanc'),
('pâte à pizza'),
('sauce tomate'),
('mozzarella'),
('vin blanc'),
('champignons'),
('lardons'),
('biscuits à la cuillère'),
('mascarpone'),
('coq'),
('poivrons'),
('courgettes'),
('aubergines'),
('pâte brisée'),
('nori'),
('avocat'),
('concombre'),
('sauce soja'),
('nouilles ramen'),
('mirin'),
('gingembre'),
('légumes variés'),
('amandes'),
('vinaigre de riz'),
('fécule de maïs'),
('Pain à burger'),
('Viande haché'),
('Salade'),
('Tortillas'),
('Salsa'),
('Guacamole'),
('Citron vert'),
('Oignons rouges'),
('Olives'),
('Fromage feta'),
("Huile d'olive"),
('Vinaigre de vin rouge'),
('Origan'),
('Orange'),
('Citron jaune'),
('Pomme'),
('eau pétillante'),
('Chorizo'),
('Fruits de mer'),
('Petits pois'),
('Safran'),
('nouilles de riz'),
('germe de soja'),
('arachides hachées'),
('échalote'),
('sauce Pad Thai');